#!/usr/bin/env php
<?php

foreach (
    [
        __DIR__ . '/',
        __DIR__ . '/../',
        __DIR__ . '/../../',
        __DIR__ . '/../../../',
    ] as $path
) {
    $file = $path . 'vendor/autoload.php';
    if (file_exists($file)) {
        define('AUTOLOAD', $file);
        break;
    }
}

unset($path);
unset($file);

require AUTOLOAD;

use IrfanTOOR\Test\TestCommand;

$cmd = new TestCommand();
$cmd->run();
